### ISSUE TITLE
Bad guard

### ISSUE THREAD

**Issue by marcfedorow** [EdikGres/Lab-work-2-dop#3]
https://github.com/EdikGres/Lab-work-2-dop/blob/45f356111d621519ab45b8aadecb07de53c9151b/Lab-work-2-dop/Functions.h#L1

Use #ifndef #define instead

**Comment by EdikGres** [comment]
Thanks for the comment, the repository is old, there is no desire to update. Sorry.
YOU TOP BRO <3
